image: golang:latest

stages:
  - test
  - build

format:
  stage: test
  script:
    - go test ./tests -v

compile:
  stage: build
  script:
    - mkdir -p mybinaries
    - go build -o mybinaries ./...
  artifacts:
    paths:
      - mybinaries
