version: '3.8'
services:
  backend:
    container_name: split-rex-backend
    build:
      dockerfile: dockerfile
      context: ./
    ports:
      - 8080:8080
    env_file:
      - .env
    volumes:
      - ./:/app
    # depends_on:
    #   - postgres

  # postgres:
  #   image: postgres
  #   container_name: split-rex-db
  #   ports:
  #     - ${DB_PORT}:${DB_PORT}
  #   environment:
  #     - POSTGRES_DB=${DB_NAME}
  #     - POSTGRES_USER=${DB_USERNAME}
  #     - POSTGRES_PASSWORD=${DB_PASSWORD}
  #   volumes:
  #     - ./.docker:/docker-entrypoint-initdb.d

volumes:
  data:
  