POST https://split-rex-backend-7v6i6rndga-et.a.run.app/register
Content-Type: application/json

{
    "name": "samuel",
    "email": "mencoba@gmail.com",
    "username": "coba",
    "password": "coba"
}

###

POST http://localhost:8080/login
Content-Type: application/json

{
    "email": "wok@gmail.com",
    "password": "wokwok"
}

###

POST http://localhost:8080/register
Content-Type: application/json

{
    "name": "wokwok",
    "email": "wok@gmail.com",
    "username": "wok",
    "password": "wokwok"
}

###

POST http://localhost:8080/login
Content-Type: application/json

{
    "email": "patrick@gmail.com",
    "password": "patrick"
}

###
POST http://localhost:8080/updateProfile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzcGxpdC1yZXgiLCJleHAiOjE2Nzk3MjYxODMsImlkIjoiNmMzNWE1MmYtNTQxZC00NTkxLTkxMGMtNmYxNjM4ZjMwODQyIn0.2Se_jS2zQSmjZb4XZl-8niOfSAQojlrId6-pjZO9_WI

{
    "name": "patututututuut",
    "color": 8
}
###
POST http://localhost:8080/updatePassword
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzcGxpdC1yZXgiLCJleHAiOjE2Nzk3MjYxODMsImlkIjoiNmMzNWE1MmYtNTQxZC00NTkxLTkxMGMtNmYxNjM4ZjMwODQyIn0.2Se_jS2zQSmjZb4XZl-8niOfSAQojlrId6-pjZO9_WI

{
    "old_password": "wokwok",
    "new_password": "sarah"
}