POST https://split-rex-backend-7v6i6rndga-et.a.run.app/register
Content-Type: application/json

{
    "name": "grace",
    "email": "grace@gmail.com",
    "username": "grace",
    "password": "grace"
}

###

POST http://localhost:8080/login
Content-Type: application/json

{
    "email": "grace@gmail.com",
    "password": "graceclaudia"
}

###

POST http://localhost:8080/register
Content-Type: application/json

{
    "name": "wikwok",
    "email": "wikwok@gmail.com",
    "username": "wikwok",
    "password": "wikwok"
}

###

POST https://split-rex-backend-7v6i6rndga-et.a.run.app/login
Content-Type: application/json

{
    "email": "ubay@gmail.com",
    "password": "ubay"
}

###
POST http://localhost:8080/updateProfile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzcGxpdC1yZXgiLCJleHAiOjE2Nzk3MjYxODMsImlkIjoiNmMzNWE1MmYtNTQxZC00NTkxLTkxMGMtNmYxNjM4ZjMwODQyIn0.2Se_jS2zQSmjZb4XZl-8niOfSAQojlrId6-pjZO9_WI

{
    "name": "patututututuut",
    "color": 8
}
###
POST http://localhost:8080/updatePassword
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzcGxpdC1yZXgiLCJleHAiOjE2Nzk3MjYxODMsImlkIjoiNmMzNWE1MmYtNTQxZC00NTkxLTkxMGMtNmYxNjM4ZjMwODQyIn0.2Se_jS2zQSmjZb4XZl-8niOfSAQojlrId6-pjZO9_WI

{
    "old_password": "wokwok",
    "new_password": "sarah"
}

###
POST http://localhost:8080/addPaymentInfo
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzcGxpdC1yZXgiLCJleHAiOjE2ODA0NjE0MDYsImlkIjoiNjI1MWFjODUtZTQzZC00Yjg4LTg3NzktNTg4MDk5ZGY1MDA4In0.L533FY_VIHk9t9DhAgPfuefOKUEJJL_bjmMFuOByC1w

{
    "payment_method": "bni",
    "account_number": 12321,
    "account_name": "patrick amadededong"
}

###
POST http://localhost:8080/deletePaymentInfo
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzcGxpdC1yZXgiLCJleHAiOjE2ODA0NjE0MDYsImlkIjoiNjI1MWFjODUtZTQzZC00Yjg4LTg3NzktNTg4MDk5ZGY1MDA4In0.L533FY_VIHk9t9DhAgPfuefOKUEJJL_bjmMFuOByC1w

{
    "payment_method": "bni",
    "account_number": 12321,
    "account_name": "patrick amadededong"
}

###
POST http://localhost:8080/editPaymentInfo
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzcGxpdC1yZXgiLCJleHAiOjE2ODA0NjE0MDYsImlkIjoiNjI1MWFjODUtZTQzZC00Yjg4LTg3NzktNTg4MDk5ZGY1MDA4In0.L533FY_VIHk9t9DhAgPfuefOKUEJJL_bjmMFuOByC1w

{
    "old_payment_method": "bni",
    "old_account_number": 12321,
    "old_account_name": "patrick amadededong",
    "new_payment_method": "bni",
    "new_account_number": 123213,
    "new_account_name": "patrick llalala"
}

###

POST http://localhost:8080/generateResetPassToken
Content-Type: application/json

{
    "email": "grace@gmail.com"
}

###
POST http://localhost:8080/verifyResetPassToken
Content-Type: application/json

{
    "email": "grace@gmail.com",
    "encrypted_token": "Yis5fl344MA1C5dCvactaRINDDyTfVjQqZcI7KM2txl1xhEMbyI=",
    "code": "lWuOSZ"
}

###
POST http://localhost:8080/changePassword
Content-Type: application/json

{
    "email": "grace@gmail.com",
    "encrypted_token": "Yis5fl344MA1C5dCvactaRINDDyTfVjQqZcI7KM2txl1xhEMbyI=",
    "code": "lWuOSZ",
    "new_password": "graceclaudia"
}