POST https://split-rex-backend-7v6i6rndga-et.a.run.app/makeFriendRequest
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzcGxpdC1yZXgiLCJleHAiOjE2ODI0MzM1OTQsImlkIjoiOGE4YWM2OTQtYjg1ZC00M2NhLWI3YzktMzhmNzk4NTJlYjdkIn0.Gdx76TzUi4cvGfWx8cw-HijxkcTsCoLyHLnaabCWNgI

{
    "friend_id": "183e04d7-c653-4c7d-aa66-3d751d4d7358"
}

###

GET https://split-rex-backend-7v6i6rndga-et.a.run.app/friendRequestSent
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzcGxpdC1yZXgiLCJleHAiOjE2Nzc5NTc5NTEsImlkIjoiYjc0YWU0ZWQtMzZjYi00NTZjLWIxZGQtOGZlZGU0MjZmMjQ0In0.GBBIPYSLcivL7Gylj020TINbP3WLyJThLL5lxg2u1PU
###

GET https://split-rex-backend-7v6i6rndga-et.a.run.app/friendRequestReceived
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzcGxpdC1yZXgiLCJleHAiOjE2Nzc5NTc5NTEsImlkIjoiYjc0YWU0ZWQtMzZjYi00NTZjLWIxZGQtOGZlZGU0MjZmMjQ0In0.GBBIPYSLcivL7Gylj020TINbP3WLyJThLL5lxg2u1PU

###
GET http://localhost:8080/userFriendList
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzcGxpdC1yZXgiLCJleHAiOjE2Nzk3NTM5NDAsImlkIjoiMTgzZTA0ZDctYzY1My00YzdkLWFhNjYtM2Q3NTFkNGQ3MzU4In0.rZjlmZwNn3SNklOof3LR8XPJiLgi9v8qP3GPXjLHsPw

### 
POST http://localhost:8080/acceptRequest
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzcGxpdC1yZXgiLCJleHAiOjE2Nzc3NjA0NzUsImlkIjoiMTgzZTA0ZDctYzY1My00YzdkLWFhNjYtM2Q3NTFkNGQ3MzU4In0.0GmCLwLQyDRjLVOxv20PAAtjj8ESREHZe8un6OrqE-s

{
    "friend_id": "6251ac85-e43d-4b88-8779-588099df5008"
}

###

POST http://localhost:8080/rejectRequest
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzcGxpdC1yZXgiLCJleHAiOjE2Nzc3NjA0NzUsImlkIjoiMTgzZTA0ZDctYzY1My00YzdkLWFhNjYtM2Q3NTFkNGQ3MzU4In0.0GmCLwLQyDRjLVOxv20PAAtjj8ESREHZe8un6OrqE-s

{
    "friend_id": "b74ae4ed-36cb-456c-b1dd-8fede426f244"
}

###

GET https://split-rex-backend-7v6i6rndga-et.a.run.app/searchUser?username=ubay
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzcGxpdC1yZXgiLCJleHAiOjE2NzgwMDMxODMsImlkIjoiNjI1MWFjODUtZTQzZC00Yjg4LTg3NzktNTg4MDk5ZGY1MDA4In0.5Aq8jPjBjDvd0B1mP6q883OqCLUX16eA_JiNFHaLdF0

###

POST http://localhost:8080/makeFriendRequest
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzcGxpdC1yZXgiLCJleHAiOjE2NzgwMDg2NTcsImlkIjoiNjI1MWFjODUtZTQzZC00Yjg4LTg3NzktNTg4MDk5ZGY1MDA4In0.wYh3J7T0UPMLN8FHbEJJGnVTlckKV--UF_5CDqNCwoo

{
    "friend_id": "6251ac85-e43d-4b88-8779-588099df5008"
}