POST http://localhost:8080/updatePayment
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzcGxpdC1yZXgiLCJleHAiOjE2Nzk4NDA5MzUsImlkIjoiNjI1MWFjODUtZTQzZC00Yjg4LTg3NzktNTg4MDk5ZGY1MDA4In0.68oLmsldMVC2-he8A76ierkeTb4uHrFiL7LVzIgRsoM

{
    "group_id" : "0b865d7f-e40e-4440-905e-eccf2caaa6ed",
    "list_payment" : [
        {
            "user_id" : "b74ae4ed-36cb-456c-b1dd-8fede426f244",
            "total_unpaid" : 10000
        },
        {
            "user_id" : "183e04d7-c653-4c7d-aa66-3d751d4d7358",
            "total_unpaid" : 20000
        }
    ]
}

###

GET http://localhost:8080/getUnsettledPayment?group_id=0b865d7f-e40e-4440-905e-eccf2caaa6ed
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzcGxpdC1yZXgiLCJleHAiOjE2ODAwNzg3MDEsImlkIjoiMTgzZTA0ZDctYzY1My00YzdkLWFhNjYtM2Q3NTFkNGQ3MzU4In0.E5RJhtKUv9vFFln_H7CT3Uyph-p11aAQSvYLZ3OQ8-U

###

POST http://localhost:8080/resolveTransaction
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzcGxpdC1yZXgiLCJleHAiOjE2ODAwNzg3MDEsImlkIjoiMTgzZTA0ZDctYzY1My00YzdkLWFhNjYtM2Q3NTFkNGQ3MzU4In0.E5RJhtKUv9vFFln_H7CT3Uyph-p11aAQSvYLZ3OQ8-U

{
    "group_id" : "0b865d7f-e40e-4440-905e-eccf2caaa6ed"
}

###

GET http://localhost:8080/getUnconfirmedPayment?group_id=0b865d7f-e40e-4440-905e-eccf2caaa6ed
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzcGxpdC1yZXgiLCJleHAiOjE2ODAwNzg3MDEsImlkIjoiMTgzZTA0ZDctYzY1My00YzdkLWFhNjYtM2Q3NTFkNGQ3MzU4In0.E5RJhtKUv9vFFln_H7CT3Uyph-p11aAQSvYLZ3OQ8-U
