POST http://localhost:8080/updatePayment
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzcGxpdC1yZXgiLCJleHAiOjE2ODI0MDQ2ODAsImlkIjoiMTc1YTIxYTQtYzAxYy00NDExLTlhZTYtZjQ5ZmNhYjgxYmQyIn0.sDLAtsfc8p6U-aTvY3d9LjinRqx_yj3c3_CRNIFaqvE

{
    "group_id" : "27ec8231-71db-4169-8680-9508c61ae559",
    "owner_expense" : 10000,
    "list_payment" : [
        {
            "user_id" : "eb4ff75a-158f-489c-ba4b-44fba94ad7a4",
            "total_unpaid" : 30000
        },
        {
            "user_id" : "8a8ac694-b85d-43ca-b7c9-38f79852eb7d",
            "total_unpaid" : 10000
        }
    ]
}

###

GET http://localhost:8080/getUnsettledPayment?group_id=0b865d7f-e40e-4440-905e-eccf2caaa6ed
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzcGxpdC1yZXgiLCJleHAiOjE2ODAwNzg3MDEsImlkIjoiMTgzZTA0ZDctYzY1My00YzdkLWFhNjYtM2Q3NTFkNGQ3MzU4In0.E5RJhtKUv9vFFln_H7CT3Uyph-p11aAQSvYLZ3OQ8-U

###

POST http://localhost:8080/resolveTransaction
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzcGxpdC1yZXgiLCJleHAiOjE2ODI0MDQ0OTUsImlkIjoiN2FhNGJjZTQtNTg0Yy00MDRiLTkyZWItZjkyZTc1NzZjMzc3In0.VQolFAL5cz-n3b6aISxtwIso_hDtGKIAVtK7mYmZGiQ

{
    "group_id" : "2105941b-9c3a-48dd-afd3-6679994b2a5d"
}

###

GET http://localhost:8080/getUnconfirmedPayment?group_id=0b865d7f-e40e-4440-905e-eccf2caaa6ed
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzcGxpdC1yZXgiLCJleHAiOjE2ODAwNzg3MDEsImlkIjoiMTgzZTA0ZDctYzY1My00YzdkLWFhNjYtM2Q3NTFkNGQ3MzU4In0.E5RJhtKUv9vFFln_H7CT3Uyph-p11aAQSvYLZ3OQ8-U

###

POST http://localhost:8080/settlePaymentOwed
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzcGxpdC1yZXgiLCJleHAiOjE2ODI0MDQ1MzYsImlkIjoiYjYwN2QzNjAtM2E2Zi00NjU0LTg3MTAtN2M0ZTlkZmNiNWFjIn0.fUQGeNAeLqHmQZvjYFOQNZrPJH4hd9fh96AQgQdFXU0

{
    "payment_id" : "34760fdf-8971-4b27-935d-298e950c2850",
    "total_paid" : 5000
}

###

POST http://localhost:8080/settlePaymentLent
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzcGxpdC1yZXgiLCJleHAiOjE2ODAwNzg3MDEsImlkIjoiMTgzZTA0ZDctYzY1My00YzdkLWFhNjYtM2Q3NTFkNGQ3MzU4In0.E5RJhtKUv9vFFln_H7CT3Uyph-p11aAQSvYLZ3OQ8-U

{
    "payment_id" : "c0137a75-cb65-41e1-8208-cb87b9490a06",
    "total_paid" : 20000
}

###

POST http://localhost:8080/confirmSettle
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzcGxpdC1yZXgiLCJleHAiOjE2ODI0MDQ0OTUsImlkIjoiN2FhNGJjZTQtNTg0Yy00MDRiLTkyZWItZjkyZTc1NzZjMzc3In0.VQolFAL5cz-n3b6aISxtwIso_hDtGKIAVtK7mYmZGiQ

{
    "payment_id" : "0a84fee1-1928-4ee9-8e76-dbf75d09f1d2"
}

###

POST http://localhost:8080/denySettle
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzcGxpdC1yZXgiLCJleHAiOjE2ODAwNzg3MDEsImlkIjoiMTgzZTA0ZDctYzY1My00YzdkLWFhNjYtM2Q3NTFkNGQ3MzU4In0.E5RJhtKUv9vFFln_H7CT3Uyph-p11aAQSvYLZ3OQ8-U

{
    "payment_id" : "c0137a75-cb65-41e1-8208-cb87b9490a06"
}

