GET http://localhost:8080/owedLentPercentage
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzcGxpdC1yZXgiLCJleHAiOjE2ODI0MDQ1MzYsImlkIjoiYjYwN2QzNjAtM2E2Zi00NjU0LTg3MTAtN2M0ZTlkZmNiNWFjIn0.fUQGeNAeLqHmQZvjYFOQNZrPJH4hd9fh96AQgQdFXU0

###
GET http://localhost:8080/paymentMutation?start_date=2023-04-23&end_date=2023-04-25
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzcGxpdC1yZXgiLCJleHAiOjE2ODI0MDQ1MzYsImlkIjoiYjYwN2QzNjAtM2E2Zi00NjU0LTg3MTAtN2M0ZTlkZmNiNWFjIn0.fUQGeNAeLqHmQZvjYFOQNZrPJH4hd9fh96AQgQdFXU0

###
GET http://localhost:8080/spendingBuddies
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzcGxpdC1yZXgiLCJleHAiOjE2ODI0MDQ0OTUsImlkIjoiN2FhNGJjZTQtNTg0Yy00MDRiLTkyZWItZjkyZTc1NzZjMzc3In0.VQolFAL5cz-n3b6aISxtwIso_hDtGKIAVtK7mYmZGiQ

###
GET http://localhost:8080/expenseChart
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzcGxpdC1yZXgiLCJleHAiOjE2ODI0MjUwNzUsImlkIjoiMTc1YTIxYTQtYzAxYy00NDExLTlhZTYtZjQ5ZmNhYjgxYmQyIn0.-JuViHho1eAFA9mW6aG-MrTtUOfK3zP9tLPKv0ohURs