package types

const (
	SUCCESS                            = "SUCCESS"

	DATA_NOT_FOUND                     = "DATA_NOT_FOUND"
	ERROR_INTERNAL_SERVER              = "ERROR_INTERNAL_SERVER"
	ERROR_BAD_REQUEST                  = "ERROR_BAD_REQUEST"
	ERROR_FAILED_REGISTER              = "ERROR_FAILED_REGISTER"
	ERROR_FAILED_LOGIN                 = "ERROR_FAILED_LOGIN"
	ERROR_JWT_SIGNING                  = "ERROR_JWT_SIGNING"
	ERROR_USERNAME_EXISTED             = "ERROR_USERNAME_EXISTED"
	ERROR_EMAIL_EXISTED                = "ERROR_EMAIL_EXISTED"
	ERROR_INVALID_TOKEN                = "ERROR_INVALID_TOKEN"
	ERROR_USER_NOT_FOUND               = "ERROR_USER_NOT_FOUND"
	ERROR_GROUP_NOT_FOUND              = "ERROR_GROUP_NOT_FOUND"
	ERROR_ALREADY_FRIEND               = "ERROR_ALREADY_FRIEND"
	ERROR_ALREADY_REQUESTED_SENT       = "ERROR_ALREADY_REQUESTED_SENT"
	ERROR_ALREADY_REQUESTED_RECEIVED   = "ERROR_ALREADY_REQUESTED_RECEIVED"
	ERROR_CANNOT_ADD_SELF              = "ERROR_CANNOT_ADD_SELF"
	ERROR_TOO_MUCH_PAYMENT             = "ERROR_TOO_MUCH_PAYMENT"
	ERROR_PAYMENT_INFO_ALREADY_EXISTED = "ERROR_PAYMENT_INFO_ALREADY_EXISTED"

	STATUS_PAYMENT_UNPAID              = "UNPAID"
	STATUS_PAYMENT_PAID                = "PAID"
	STATUS_PAYMENT_PENDING             = "PENDING"
	
	TYPE_GROUP_OWED                    = "OWED"
	TYPE_GROUP_LENT                    = "LENT"
	TYPE_GROUP_EQUAL                   = "EQUAL"
)
