package types

const (
	SUCCESS                = "SUCCESS"
	ERROR_INTERNAL_SERVER  = "ERROR_INTERNAL_SERVER"
	ERROR_BAD_REQUEST      = "ERROR_BAD_REQUEST"
	ERROR_FAILED_REGISTER  = "ERROR_FAILED_REGISTER"
	ERROR_FAILED_LOGIN     = "ERROR_FAILED_LOGIN"
	ERROR_JWT_SIGNING      = "ERROR_JWT_SIGNING"
	ERROR_USERNAME_EXISTED = "ERROR_USERNAME_EXISTED"
	ERROR_EMAIL_EXISTED    = "ERROR_EMAIL_EXISTED"
)
