package types

const (
	SUCCESS                 = "SUCCESS"
	DATA_NOT_FOUND          = "DATA_NOT_FOUND"
	ERROR_INTERNAL_SERVER   = "ERROR_INTERNAL_SERVER"
	ERROR_BAD_REQUEST       = "ERROR_BAD_REQUEST"
	ERROR_FAILED_REGISTER   = "ERROR_FAILED_REGISTER"
	ERROR_FAILED_LOGIN      = "ERROR_FAILED_LOGIN"
	ERROR_JWT_SIGNING       = "ERROR_JWT_SIGNING"
	ERROR_USERNAME_EXISTED  = "ERROR_USERNAME_EXISTED"
	ERROR_EMAIL_EXISTED     = "ERROR_EMAIL_EXISTED"
	ERROR_INVALID_TOKEN     = "ERROR_INVALID_TOKEN"
	ERROR_USER_NOT_FOUND    = "ERROR_USER_NOT_FOUND"
	ERROR_GROUP_NOT_FOUND   = "ERROR_GROUP_NOT_FOUND"
	ERROR_ALREADY_FRIEND    = "ERROR_ALREADY_FRIEND"
	ERROR_ALREADY_REQUESTED = "ERROR_ALREADY_REQUESTED"
	ERROR_CANNOT_ADD_SELF   = "ERROR_CANNOT_ADD_SELF"
)
